// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { CountryDB } from './country-db';
import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { HelloDB } from './hello-db'

@Injectable({
  providedIn: 'root'
})
export class CountryService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  CountryServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private countrysUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.countrysUrl = origin + '/api/ngimportissue/go/v1/countrys';
  }

  /** GET countrys from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryDB[]> {
    return this.getCountrys(GONG__StackPath, frontRepo)
  }
  getCountrys(GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<CountryDB[]>(this.countrysUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<CountryDB[]>('getCountrys', []))
      );
  }

  /** GET country by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryDB> {
    return this.getCountry(id, GONG__StackPath, frontRepo)
  }
  getCountry(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.countrysUrl}/${id}`;
    return this.http.get<CountryDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched country id=${id}`)),
      catchError(this.handleError<CountryDB>(`getCountry id=${id}`))
    );
  }

  /** POST: add a new country to the server */
  post(countrydb: CountryDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryDB> {
    return this.postCountry(countrydb, GONG__StackPath, frontRepo)
  }
  postCountry(countrydb: CountryDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    if (countrydb.Hello != undefined) {
      countrydb.CountryPointersEncoding.HelloID.Int64 = countrydb.Hello.ID
      countrydb.CountryPointersEncoding.HelloID.Valid = true
    }
    countrydb.Hello = undefined
    countrydb.CountryPointersEncoding.AlternateHellos = []
    for (let _hello of countrydb.AlternateHellos) {
      countrydb.CountryPointersEncoding.AlternateHellos.push(_hello.ID)
    }
    countrydb.AlternateHellos = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<CountryDB>(this.countrysUrl, countrydb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        countrydb.Hello = frontRepo.Hellos.get(countrydb.CountryPointersEncoding.HelloID.Int64)
        countrydb.AlternateHellos = new Array<HelloDB>()
        for (let _id of countrydb.CountryPointersEncoding.AlternateHellos) {
          let _hello = frontRepo.Hellos.get(_id)
          if (_hello != undefined) {
            countrydb.AlternateHellos.push(_hello!)
          }
        }
        // this.log(`posted countrydb id=${countrydb.ID}`)
      }),
      catchError(this.handleError<CountryDB>('postCountry'))
    );
  }

  /** DELETE: delete the countrydb from the server */
  delete(countrydb: CountryDB | number, GONG__StackPath: string): Observable<CountryDB> {
    return this.deleteCountry(countrydb, GONG__StackPath)
  }
  deleteCountry(countrydb: CountryDB | number, GONG__StackPath: string): Observable<CountryDB> {
    const id = typeof countrydb === 'number' ? countrydb : countrydb.ID;
    const url = `${this.countrysUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<CountryDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted countrydb id=${id}`)),
      catchError(this.handleError<CountryDB>('deleteCountry'))
    );
  }

  /** PUT: update the countrydb on the server */
  update(countrydb: CountryDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryDB> {
    return this.updateCountry(countrydb, GONG__StackPath, frontRepo)
  }
  updateCountry(countrydb: CountryDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryDB> {
    const id = typeof countrydb === 'number' ? countrydb : countrydb.ID;
    const url = `${this.countrysUrl}/${id}`;

    // insertion point for reset of pointers (to avoid circular JSON)
    // and encoding of pointers
    if (countrydb.Hello != undefined) {
      countrydb.CountryPointersEncoding.HelloID.Int64 = countrydb.Hello.ID
      countrydb.CountryPointersEncoding.HelloID.Valid = true
    }
    countrydb.Hello = undefined
    countrydb.CountryPointersEncoding.AlternateHellos = []
    for (let _hello of countrydb.AlternateHellos) {
      countrydb.CountryPointersEncoding.AlternateHellos.push(_hello.ID)
    }
    countrydb.AlternateHellos = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<CountryDB>(url, countrydb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        countrydb.Hello = frontRepo.Hellos.get(countrydb.CountryPointersEncoding.HelloID.Int64)
        countrydb.AlternateHellos = new Array<HelloDB>()
        for (let _id of countrydb.CountryPointersEncoding.AlternateHellos) {
          let _hello = frontRepo.Hellos.get(_id)
          if (_hello != undefined) {
            countrydb.AlternateHellos.push(_hello!)
          }
        }
        // this.log(`updated countrydb id=${countrydb.ID}`)
      }),
      catchError(this.handleError<CountryDB>('updateCountry'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in CountryService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("CountryService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
