// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { HelloDB } from './hello-db';
import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class HelloService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  HelloServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private hellosUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.hellosUrl = origin + '/api/ngimportissue/go/v1/hellos';
  }

  /** GET hellos from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<HelloDB[]> {
    return this.getHellos(GONG__StackPath, frontRepo)
  }
  getHellos(GONG__StackPath: string, frontRepo: FrontRepo): Observable<HelloDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<HelloDB[]>(this.hellosUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<HelloDB[]>('getHellos', []))
      );
  }

  /** GET hello by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<HelloDB> {
    return this.getHello(id, GONG__StackPath, frontRepo)
  }
  getHello(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<HelloDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.hellosUrl}/${id}`;
    return this.http.get<HelloDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched hello id=${id}`)),
      catchError(this.handleError<HelloDB>(`getHello id=${id}`))
    );
  }

  /** POST: add a new hello to the server */
  post(hellodb: HelloDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<HelloDB> {
    return this.postHello(hellodb, GONG__StackPath, frontRepo)
  }
  postHello(hellodb: HelloDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<HelloDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<HelloDB>(this.hellosUrl, hellodb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted hellodb id=${hellodb.ID}`)
      }),
      catchError(this.handleError<HelloDB>('postHello'))
    );
  }

  /** DELETE: delete the hellodb from the server */
  delete(hellodb: HelloDB | number, GONG__StackPath: string): Observable<HelloDB> {
    return this.deleteHello(hellodb, GONG__StackPath)
  }
  deleteHello(hellodb: HelloDB | number, GONG__StackPath: string): Observable<HelloDB> {
    const id = typeof hellodb === 'number' ? hellodb : hellodb.ID;
    const url = `${this.hellosUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<HelloDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted hellodb id=${id}`)),
      catchError(this.handleError<HelloDB>('deleteHello'))
    );
  }

  /** PUT: update the hellodb on the server */
  update(hellodb: HelloDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<HelloDB> {
    return this.updateHello(hellodb, GONG__StackPath, frontRepo)
  }
  updateHello(hellodb: HelloDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<HelloDB> {
    const id = typeof hellodb === 'number' ? hellodb : hellodb.ID;
    const url = `${this.hellosUrl}/${id}`;

    // insertion point for reset of pointers (to avoid circular JSON)
    // and encoding of pointers

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<HelloDB>(url, hellodb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated hellodb id=${hellodb.ID}`)
      }),
      catchError(this.handleError<HelloDB>('updateHello'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in HelloService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("HelloService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
